### ISSUE TITLE
How to get dynamic agent jobs?get JSDL

### ISSUE THREAD

**Issue by WolfCat-ICE** [WAdev0/TWS_REST_API_Shell_script_samples#1]
I tried to get it using a url, but the prompt did not exist
https://192.168.0.211:31116/twsd/engine/executor?executor=BINGTEST213
AWSJCS021E The application job plug-in with ID "BINGTEST213" cannot be found.

**Comment by fmossott** [comment]
Not sure I've got your scenario.
The JSDL for the job is within the job definition, you may look at GET /model/jobdefinition

**Comment by WolfCat-ICE** [comment]
Thank you, the get job does not show the agent job information, the "taskString" only shows the name of the agent job.
I want to get information about “djob_tiger1”，But I don't know which API to use.
`https://192.168.0.211:31116/twsd/model/jobdefinition?name=DJOB1&workstationName=DWB`
{
    "definedByJsdl": false,
    "header": {
        "description": "Added by composer.1",
        "id": "fe819151-4e74-3dff-9429-b2529474376c",
        "isCommand": false,
        "jobDefinitionKey": {
            "name": "DJOB1",
            "workstationName": "DWB"
        },
        "lastRunTime": "2018-04-22T09:56:43.000+0000",
        "lockData": {
            "lockedBy": "tws",
            "lockedSession": "tws",
            "lockedTime": "2019-02-22T07:50:14.296+0000"
        },
        "modifyData": {
            "modifiedBy": "tws",
            "modifiedTime": "2019-02-22T07:58:08.093+0000"
        },
        "taskType": "BROKER",
        "userLogin": "^USERTWS^"
    },
    "isInteractive": false,
    "normalElapsedTime": 1459222,
    "recoveryOption": "STOP",
    "taskString": "djob_tiger1",
    "workstationId": "f63e6b16-6d5a-39ab-9d2d-59341994c2a4"
}

**Comment by WolfCat-ICE** [comment]
Sorry I described Broker as agent.
I want to manage jobs on the Broker through the API, But I don't know which API to use.
![image](https://user-images.githubusercontent.com/45056430/53323579-8469c280-3919-11e9-994b-d44f73d9abcb.png)

**Comment by fmossott** [comment]
OK, now I see.
You want to interact directly with Broker, this is not part of the twsd APIs.
Having the JSDL directly on Broker is not suggested and will be deprecated, replaced by static and dynamic pools and JSDL within the job definition.
The Broker has internal APIs (SOAP until 9.4 / REST since 9.5) but they have never been published.

**Comment by WolfCat-ICE** [comment]
I really appreciate your help :-)
Can the IBM Workload Scheduler  Java API  do this?

**Comment by fmossott** [comment]
No sorry, same answer using the Java APIs.
Is using Pools and Job definitions an option for you?
If not, can you explain why so that we can better understand the constraints?
If Broker APIs are the only options for you, we can try to figureout how to expose them, but be aware that the SOAP APIs has been replaced in 9.5 with REST APIs, so you would need different implementations depending on the version

**Comment by WolfCat-ICE** [comment]
**In fact, I want to modify the parameters value in JSDL through the Broker APIs, such as ${script}, ${username}, ${password}, ${hostName}.**
```
<?xml version="1.0" encoding="UTF-8"?>
<jsdl:jobDefinition xmlns:jsdl="http://www.ibm.com/xmlns/prod/scheduling/1.0/jsdl" xmlns:jsdle="http://www.ibm.com/xmlns/prod/scheduling/1.0/jsdle" name="djob_tiger1">
  <jsdl:application name="executable">
    <jsdle:executable>
      <jsdle:script>${script}</jsdle:script>
      <jsdle:credential>
        <jsdle:userName>${username}</jsdle:userName>
        <jsdle:password>${password}</jsdle:password>
      </jsdle:credential>
    </jsdle:executable>
  </jsdl:application>
  <jsdl:resources>
    <jsdl:candidateHosts>
      ${hostName}
    </jsdl:candidateHosts>
  </jsdl:resources>
  <jsdl:optimization name="JPT_BestResource">
    <jsdl:objective propertyObjective="minimize" resourcePropertyName="CPUUtilization" resourceType="ComputerSystem"/>
  </jsdl:optimization>
</jsdl:jobDefinition>
```
**May I ask if this definition can be passed parameter values via PUT /model/jobdefinition/{jobdefinitionId}?**
"taskString": "djob_tiger10  -var script=value,username=tws,password=test,hostName=TWSMDM1_1",
**Or there are other ways to do it,I didn't know how to do that.**

**Something like this Example 
https://192.168.0.211:31116/twsd/model/jobdefinition/00c669bc-3357-3704-9f28-4adccce61e3f**
```
{
    "definedByJsdl": false,
    "header": {
        "id": "00c669bc-3357-3704-9f28-4adccce61e3f",
        "isCommand": false,
        "jobDefinitionKey": {
            "name": "DJOB10",
            "workstationName": "DWB"
        },
        "taskType": "BROKER",
        "userLogin": "tws"
    },
    "taskString": "djob_tiger10  -var script=value,username=tws,password=***,hostName=TWSMDM1_1",
    "workstationId": "f63e6b16-6d5a-39ab-9d2d-59341994c2a4"
}
```

**Comment by fmossott** [comment]
Again, I suggest to use agent workstations, advanced job types and pools, so that you can just work on the TWS side and not have to handle JSDL as a separate definition and map them with the TWS job:
https://www.ibm.com/support/knowledgecenter/en/SSGSPN_9.5.0/com.ibm.tivoli.itws.doc_9.5/distr/src_ref/awsrgjobdefnexec.htm
https://www.ibm.com/support/knowledgecenter/en/SSGSPN_9.5.0/com.ibm.tivoli.itws.doc_9.5/distr/src_ref/awsrgdynamicwks.htm

If you have a specific reason to use jsdls that I still don't see, username, password and task string variables are passed automatically for every job:
https://www.ibm.com/support/knowledgecenter/en/SSGSPN_9.5.0/com.ibm.tivoli.itws.doc_9.5/distr/src_swd/awsbrtwsvars.htm

You can pass other variables as you are doing or defining JSDL templates
https://www.ibm.com/support/knowledgecenter/en/SSGSPN_9.5.0/com.ibm.tivoli.itws.doc_9.5/distr/src_swd/awsbrusingjsdljobdefinitiontemplates.htm

The PUT API you are indicating is to modify a job definition, that is something that should not be done at every job submission.
In order to pass different values at every submission look at

- Submit an ad hoc job without using a job definition:
POST /plan/{planId}/job/action/submit_ad_hoc_job

- Create the job defintion using TWS variables (^VARNAME^) and include that in a job stream, then submit it like in this example:
https://github.com/WAdev0/TWS_REST_API_Python_samples/blob/master/python/submit_jobstream.py

Same APIs can be used if you pass to agent workstations, advanced job types and pools

**Comment by WolfCat-ICE** [comment]
Thank you very much for the trouble
